Price)).reduce((a,l)=>a+l.salePrice,0));}const weekR=w.reduce((a,v)=>a+v,0),totalR=allLogs.filter(l=>l.salePrice).reduce((a,l)=>a+l.salePrice,0);el.innerHTML=`<div class="admin-stats-grid"><div class="admin-stat"><div class="stat-val green">${fmt(todayR)}</div><div class="stat-label">Today</div></div><div class="admin-stat"><div class="stat-val accent">${fmt(weekR)}</div><div class="stat-label">This Week</div></div><div class="admin-stat"><div class="stat-val">${fmt(totalR)}</div><div class="stat-label">All Time</div></div><div class="admin-stat"><div class="stat-val">${allLogs.reduce((a,l)=>a+l.qty,0)}</div><div class="stat-label">Units Sold</div></div></div>`;}
async function renderTopProds(){const el=document.getElementById("topProductsReport");if(!el)return;const h=await getHistory(),allLogs=Object.values(h).flat().filter(l=>l.type==="Sale"),pm={};allLogs.forEach(l=>{if(!pm[l.product])pm[l.product]={qty:0,rev:0};pm[l.product].qty+=l.qty;pm[l.product].rev+=l.salePrice||0;});const sorted=Object.entries(pm).sort((a,b)=>b[1].rev-a[1].rev).slice(0,5);if(!sorted.length){el.innerHTML=`<div class="empty-msg" style="padding:16px">Koi sales nahi</div>`;return;}let html=`<div style="overflow-x:auto"><table class="stock-table"><thead><tr><th>#</th><th>Product</th><th>Units</th><th>Revenue</th></tr></thead><tbody>`;sorted.forEach(([n,d],i)=>{html+=`<tr><td>${i+1}</td><td class="p-name">${n}</td><td>${d.qty}</td><td style="color:var(--green);font-weight:700">${fmt(d.rev)}</td></tr>`;});html+=`</tbody></table></div>`;el.innerHTML=html;}
async function genSalesReport(){const from=document.getElementById("reportFrom").value,to=document.getElementById("reportTo").value,el=document.getElementById("salesReportResult"),btn=document.getElementById("exportSalesBtn");if(!from||!to){el.innerHTML=`<div style="color:var(--red);font-size:13px;margin-top:8px">Date range select karo</div>`;return;}const h=await getHistory();let rev=0,units=0,trans=0,days=0;const d=new Date(from);while(d<=new Date(to)){const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,logs=(h[k]||[]).filter(l=>l.type==="Sale");if(logs.length){rev+=logs.filter(l=>l.salePrice).reduce((a,l)=>a+l.salePrice,0);units+=logs.reduce((a,l)=>a+l.qty,0);trans+=logs.length;days++;}d.setDate(d.getDate()+1);}el.innerHTML=`<div class="admin-stats-grid" style="margin-top:10px"><div class="admin-stat"><div class="stat-val green">${fmt(rev)}</div><div class="stat-label">Revenue</div></div><div class="admin-stat"><div class="stat-val">${units}</div><div class="stat-label">Units</div></div><div class="admin-stat"><div class="stat-val accent">${days}</div><div class="stat-label">Days</div></div><div class="admin-stat"><div class="stat-val">${trans}</div><div class="stat-label">Transactions</div></div></div>`;btn.style.display=days>0?"block":"none";}
async function dlSalesReport(){const from=document.getElementById("reportFrom").value,to=document.getElementById("reportTo").value,h=await getHistory();let csv="Date,Product,Category,Type,Qty,Balance,Amount\n";const d=new Date(from);while(d<=new Date(to)){const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;(h[k]||[]).filter(l=>l.type==="Sale").forEach(l=>{csv+=`"${fmtD(k)}","${l.product}","${l.cat}","${l.type}",${l.qty},${l.balance},"${l.salePrice?fmt(l.salePrice):""}"\n`;});d.setDate(d.getDate()+1);}dlFile(csv,`sales_${from}_to_${to}.csv`,"text/csv");showToast("Sales report downloaded");}
async function dlStockSnapshot(){const filter=document.getElementById("snapshotFilter").value,st=await getStock(),s=await getSettings(),low=s.lowStockLevel||5,all=[];Object.entries(PRODUCTS).forEach(([cat,items])=>items.forEach(e=>{const n=pn(e),qty=st[n]||0;all.push({cat,name:n,code:pc(e),qty});}));let flt=all;if(filter==="stocked")flt=all.filter(p=>p.qty>0);else if(filter==="low")flt=all.filter(p=>p.qty<=low);else if(filter==="out")flt=all.filter(p=>p.qty===0);if(!flt.length){showMsg("snapshotMsg","Koi data nahi",true);return;}let csv="Category,Product,Code,Stock,Status\n";flt.forEach(p=>{const st2=p.qty===0?"Out":p.qty<=low?"Low":"In Stock";csv+=`"${p.cat}","${p.name}","${p.code||""}",${p.qty},"${st2}"\n`;});dlFile(csv,`snapshot_${today()}.csv`,"text/csv");showMsg("snapshotMsg",`✅ ${flt.length} products exported`,false);showToast("Snapshot downloaded");}
async function renderBackupStatus(){const el=document.getElementById("backupStatus");if(!el)return;const s=await getSettings(),last=s.lastBackup;if(!last){el.innerHTML=`<div class="backup-warn">⚠️ Koi backup nahi hua! Zaroor backup lo.</div>`;return;}const days=Math.round((new Date()-new Date(last))/864e5);el.innerHTML=`<div class="${days>7?"backup-warn":"backup-ok"}">Last: ${fmtD(last.slice(0,10))} (${days} din pehle)${days>7?" — Backup karo!":""}</div>`;}
async function renderStorageInfo(){const el=document.getElementById("storageInfo");if(!el)return;const info=await getStorageInfo();el.innerHTML=`<div style="font-size:12px;color:var(--muted);margin-top:6px">${info.idbInfo} | ${info.lsInfo}</div>`;}
async function renderAdminStats(){const[st,pr,s,h,exp]=await Promise.all([getStock(),getPricing(),getSettings(),getHistory(),getExpiry()]);const allLogs=Object.values(h).flat(),saleLogs=allLogs.filter(l=>l.type==="Sale"),rev=saleLogs.filter(l=>l.salePrice).reduce((a,l)=>a+l.salePrice,0),all=Object.values(PRODUCTS).flat().map(e=>pn(e)),low=s.lowStockLevel||5;const el=document.getElementById("adminStatsGrid");if(!el)return;el.innerHTML=`<div class="admin-stat"><div class="stat-val">${all.length}</div><div class="stat-label">Products</div></div><div class="admin-stat"><div class="stat-val ok">${all.filter(p=>st[p]>0).length}</div><div class="stat-label">In Stock</div></div><div class="admin-stat"><div class="stat-val red">${all.filter(p=>st[p]===0).length}</div><div class="stat-label">Out</div></div><div class="admin-stat"><div class="stat-val yellow">${all.filter(p=>st[p]>0&&st[p]<=low).length}</div><div class="stat-label">Low</div></div><div class="admin-stat"><div class="stat-val accent">${Object.keys(pr).length}</div><div class="stat-label">Priced</div></div><div class="admin-stat"><div class="stat-val">${exp.filter(e=>e.status==="active").length}</div><div class="stat-label">Batches</div></div><div class="admin-stat"><div class="stat-val">${saleLogs.reduce((a,l)=>a+l.qty,0)}</div><div class="stat-label">Units Sold</div></div><div class="admin-stat"><div class="stat-val green">${rev>0?fmt(rev):"—"}</div><div class="stat-label">Revenue</div></div><div class="admin-stat"><div class="stat-val">${Object.keys(PRODUCTS).length}</div><div class="stat-label">Categories</div></div><div class="admin-stat"><div class="stat-val">${allLogs.length}</div><div class="stat-label">Logs</div></div>`;}
async function renderCatBreakdown(){const el=document.getElementById("catBreakdown");if(!el)return;const[st,pr,s]=await Promise.all([getStock(),getPricing(),getSettings()]);const low=s.lowStockLevel||5;let html=`<div style="overflow-x:auto"><table class="stock-table"><thead><tr><th>Category</th><th>Products</th><th>In Stock</th><th>Low</th><th>Out</th><th>Priced</th></tr></thead><tbody>`;Object.entries(PRODUCTS).forEach(([cat,items])=>{const names=items.map(e=>pn(e));html+=`<tr><td class="p-name">${cat}</td><td>${names.length}</td><td style="color:var(--green)">${names.filter(n=>st[n]>low).length}</td><td style="color:var(--yellow)">${names.filter(n=>st[n]>0&&st[n]<=low).length}</td><td style="color:var(--red)">${names.filter(n=>!st[n]||st[n]===0).length}</td><td style="color:var(--accent)">${names.filter(n=>pr[n]).length}</td></tr>`;});html+=`</tbody></table></div>`;el.innerHTML=html;}
async function dlPricingCSV(){const p=await getPricing(),keys=Object.keys(p);if(!keys.length){showToast("Koi pricing set nahi");return;}let csv="Product,MRP,Sale Price,Disc%,Note\n";keys.forEach(n=>{const pr=p[n];csv+=`"${n}",${pr.mrp||""},${pr.discountPrice||""},${pr.discountPct||0},"${pr.note||""}"\n`;});dlFile(csv,`pricing_${today()}.csv`,"text/csv");showToast("Pricing CSV downloaded");}
async function doImport(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async function(e){const ok=await importBackup(e.target.result);if(ok){showMsg("importMsg","✅ Import successful! Reloading...",false);setTimeout(()=>location.reload(),2000);}else showMsg("importMsg","❌ Invalid backup file",true);};reader.readAsText(file);}
async function doReset(type){const msgs={history:"Poora history delete karna chahte ho?",stock:"Sab ka stock 0 karna chahte ho?",pricing:"Sab ki pricing delete karna chahte ho?",expiry:"Sab expiry entries delete karna chahte ho?",everything:"⚠️ SAB KUCH DELETE HOGA! Pakka?"};if(!confirm(msgs[type]||"Sure?"))return;if(type==="everything"&&!confirm("Are you 100% sure? Undo nahi hoga!"))return;if(type==="everything"){await Promise.all(["stock","history","pricing","expiry"].map(k=>resetTable(k)));}else await resetTable(type);showToast(`${type} reset done!`);await renderDash();await renderHist();renderPricingTable();await renderExpSummary();await renderExpList();}

// ── CATALOG ──────────────────────────────────────────────────────
let _sCat=null;
async function renderCatList(){const list=document.getElementById("catList");if(!list)return;const cats=Object.keys(_catalog);if(!cats.length){list.innerHTML=`<div class="cat-empty">Koi category nahi</div>`;return;}list.innerHTML=cats.map(c=>{const count=_catalog[c].length,active=c===_sCat?" active":"";return`<div class="cat-list-item${active}" onclick="selCat('${esc(c)}')"><span class="cat-item-name">${esc(c)}</span><span class="cat-item-count">${count}</span><span class="cat-item-actions"><button class="icon-btn" onclick="event.stopPropagation();openRenameCat('${esc(c)}')">✏️</button><button class="icon-btn red" onclick="event.stopPropagation();delCat('${esc(c)}')">🗑️</button></span></div>`;}).join("");}
function selCat(c){_sCat=c;renderCatList();renderProdList(c);document.getElementById("prodColTitle").textContent=`📂 ${c}`;document.getElementById("addProdBtn").style.display="";}
function renderProdList(cat){const list=document.getElementById("prodList");if(!list)return;const items=_catalog[cat]||[];if(!items.length){list.innerHTML=`<div class="cat-empty">Koi product nahi</div>`;return;}list.innerHTML=items.map((p,i)=>`<div class="prod-list-item"><div class="prod-item-info"><span class="prod-item-name">${esc(p.name)}</span>${p.code?`<span class="prod-item-code">${esc(p.code)}</span>`:""}</div><span class="cat-item-actions"><button class="icon-btn" onclick="moveProd('${esc(cat)}',${i},-1)" ${i===0?"disabled":""}>▲</button><button class="icon-btn" onclick="moveProd('${esc(cat)}',${i},1)" ${i===items.length-1?"disabled":""}>▼</button><button class="icon-btn" onclick="openEditProd('${esc(cat)}',${i})">✏️</button><button class="icon-btn red" onclick="delProd('${esc(cat)}',${i})">🗑️</button></span></div>`).join("");}
function openAddCat(){document.getElementById("catModalTitle").textContent="New Category";document.getElementById("catModalInput").value="";document.getElementById("catModalOld").value="";document.getElementById("catModalMsg").className="msg-box";document.getElementById("catModal").style.display="flex";setTimeout(()=>document.getElementById("catModalInput").focus(),100);}
function openRenameCat(cat){document.getElementById("catModalTitle").textContent="Rename Category";document.getElementById("catModalInput").value=cat;document.getElementById("catModalOld").value=cat;document.getElementById("catModalMsg").className="msg-box";document.getElementById("catModal").style.display="flex";setTimeout(()=>document.getElementById("catModalInput").focus(),100);}
function closeCatModal(){document.getElementById("catModal").style.display="none";}
async function saveCatModal(){const newN=document.getElementById("catModalInput").value.trim(),oldN=document.getElementById("catModalOld").value;if(!newN){showMsg("catModalMsg","Name daalo",true);return;}if(oldN){if(newN===oldN){closeCatModal();return;}if(_catalog[newN]){showMsg("catModalMsg","Name pehle se hai",true);return;}_catalog[newN]=_catalog[oldN];delete _catalog[oldN];if(_sCat===oldN)_sCat=newN;showToast("Renamed ✅");}else{if(_catalog[newN]){showMsg("catModalMsg","Category pehle se hai",true);return;}_catalog[newN]=[];_sCat=newN;showToast(`"${newN}" added ✅`);}await setCatalogData(_catalog);rebuildPROD();await refreshDrops();closeCatModal();renderCatList();if(_sCat)selCat(_sCat);showMsg("catalogMsg",`✅ "${newN}" saved!`,false);}
async function delCat(cat){if(!confirm(`"${cat}" mein ${(_catalog[cat]||[]).length} products hain. Delete?`))return;delete _catalog[cat];if(_sCat===cat){_sCat=null;document.getElementById("prodList").innerHTML="";document.getElementById("prodColTitle").textContent="← Select category";document.getElementById("addProdBtn").style.display="none";}await setCatalogData(_catalog);rebuildPROD();await refreshDrops();showToast(`"${cat}" deleted`);showMsg("catalogMsg","✅ Deleted",false);renderCatList();}
function openAddProd(){if(!_sCat)return;document.getElementById("prodModalTitle").textContent=`New Product in "${_sCat}"`;["prodModalName","prodModalCode","prodModalOld"].forEach(id=>document.getElementById(id).value="");document.getElementById("prodModalCat").value=_sCat;document.getElementById("prodModalMsg").className="msg-box";document.getElementById("prodModal").style.display="flex";setTimeout(()=>document.getElementById("prodModalName").focus(),100);}
function openEditProd(cat,idx){const p=_catalog[cat][idx];document.getElementById("prodModalTitle").textContent="Edit Product";document.getElementById("prodModalName").value=p.name;document.getElementById("prodModalCode").value=p.code||"";document.getElementById("prodModalOld").value=p.name;document.getElementById("prodModalCat").value=cat;document.getElementById("prodModalMsg").className="msg-box";document.getElementById("prodModal").style.display="flex";setTimeout(()=>document.getElementById("prodModalName").focus(),100);}
function closeProdModal(){document.getElementById("prodModal").style.display="none";}
async function saveProdModal(){const cat=document.getElementById("prodModalCat").value,newN=document.getElementById("prodModalName").value.trim(),code=document.getElementById("prodModalCode").value.trim(),oldN=document.getElementById("prodModalOld").value;if(!newN){showMsg("prodModalMsg","Product name daalo",true);return;}const items=_catalog[cat]||[];if(oldN){const idx=items.findIndex(p=>p.name===oldN);if(idx===-1){showMsg("prodModalMsg","Product nahi mila",true);return;}items[idx]={name:newN,code};showToast("Updated ✅");}else{if(items.find(p=>p.name===newN)){showMsg("prodModalMsg","Product pehle se hai",true);return;}items.push({name:newN,code});showToast("Added ✅");}_catalog[cat]=items;await setCatalogData(_catalog);rebuildPROD();await refreshDrops();closeProdModal();renderProdList(cat);showMsg("catalogMsg",`✅ "${newN}" saved!`,false);}
async function delProd(cat,idx){const p=_catalog[cat][idx];if(!confirm(`"${p.name}" delete?`))return;_catalog[cat].splice(idx,1);await setCatalogData(_catalog);rebuildPROD();await refreshDrops();renderProdList(cat);showToast("Deleted");}
async function moveProd(cat,idx,dir){const items=_catalog[cat],ni=idx+dir;if(ni<0||ni>=items.length)return;[items[idx],items[ni]]=[items[ni],items[idx]];_catalog[cat]=items;await setCatalogData(_catalog);rebuildPROD();renderProdList(cat);}

window.addEventListener("DOMContentLoaded", init);
